name: Lint dockerfiles

on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Lint by hadolint
        run: |
          for f in $(find $GITHUB_WORKSPACE -name Dockerfile*); do
            docker run --rm -i hadolint/hadolint < $f
          done
